name: haskell-setup
on:
  push:
    branches:
      - master
      - ci*
  pull_request:
    branches:
      - master
      - ci*

defaults:
  run:
    shell: bash

jobs:
  haskell-setup:
    name: ${{ matrix.os }} haskell-setup ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        ghc: [9.6.1, 9.4.4, 9.2.7, 9.0.2, 8.10.7]
    steps:

    - uses: actions/checkout@v3

    - name: Install GHC with haskell/actions/setup
      uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-update: true

    - name: Configure
      run: cabal configure --enable-tests --enable-benchmarks

    - name: Build dependencies
      run: cabal build all --dependencies-only

    - name: Build
      run: cabal build all

    - name: Run tests
      run: cabal test all
